export const SIGNUP_LOADING = 'SIGNUP_LOADING'; 
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_LOADING = 'LOGIN_LOADING'; 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const ADDFUNDS_LOADING = 'ADDFUNDS_LOADING'; 
export const ADDFUNDS_SUCCESS = 'ADDFUNDS_SUCCESS';
export const ADDFUNDS_ERROR = 'ADDFUNDS_ERROR';