export const SIGNUP_LOADING = 'SIGNUP_LOADING'; 
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_LOADING = 'LOGIN_LOADING'; 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const ADDFUNDS_LOADING = 'ADDFUNDS_LOADING'; 
export const ADDFUNDS_SUCCESS = 'ADDFUNDS_SUCCESS';
export const ADDFUNDS_ERROR = 'ADDFUNDS_ERROR';

export const PROFILE_LOADING = 'PROFILE_LOADING'; 
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const WITHDRAWAL_LOADING = 'WITHDRAWAL_LOADING'; 
export const WITHDRAWAL_SUCCESS = 'WITHDRAWAL_SUCCESS';
export const WITHDRAWAL_ERROR = 'WITHDRAWAL_ERROR';